name: Produce packages

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # every hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build latest
        run: |
          for ((i=1; i<=5; i++))
          do
            randomString=$(LC_ALL=C tr -dc A-Za-z0-9 </dev/urandom | head -c 10 2>/dev/null || echo RANDOM)
            echo "FROM alpine as builder" > Dockerfile
            echo "RUN echo \"$randomString\" > test.txt" >> Dockerfile
            echo "FROM scratch" >> Dockerfile
            echo "COPY --from=builder /test.txt ." >> Dockerfile

            imageName="ghcr.io/snok/container-retention-policy:test-${i}"

            docker build -f Dockerfile -t "$imageName" --push .

            for ((j=1; j<=3; j++))
            do
              docker tag "$imageName" "ghcr.io/snok/container-retention-policy:test-${i}-${j}"
              docker push "ghcr.io/snok/container-retention-policy:test-${i}-${j}"
            done
          done
