name: Build container image

on:
  workflow_dispatch:
    inputs:
      version-tag:
        description: The image tag to build for
        required: true
        type: string
  release:
    types:
      - created
      - edited

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set image tag
        id: set-image-tag
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "image-tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "image-tag=${{ github.event.inputs.version-tag }}" >> $GITHUB_OUTPUT
          fi
      - name: Build multi-platform image
        run: |
          imageName="ghcr.io/snok/container-retention-policy:${{ steps.set-image-tag.outputs.image-tag }}"
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -f Dockerfile -t "$imageName" --push .
