name: Produce packages

on:
  workflow_dispatch:
  release:
    types:
      - created
      - edited

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build release version
        run: |
          imageName="ghcr.io/snok/container-retention-policy:${{ github.ref_name }}"
          docker buildx build --platform linux/amd64,linux/arm64 -f Dockerfile -t "$imageName" --push .

      - name: Build latest
        run: |
          imageName="ghcr.io/snok/container-retention-policy:latest"
          docker buildx build --platform linux/amd64,linux/arm64 -f Dockerfile -t "$imageName" --push .
