name: Temp test

on: push

jobs:
  foo:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "${{ runner.arch}}"
      - run: echo "${{ runner.os}}"
      - uses: actions/checkout@v4
      - run: ./artifacts/container-retention-policy-${{ runner.arch }}-${{ runner.os }} --help
